### ISSUE TITLE
donation

### ISSUE THREAD

**Issue by Wet-9** [Tizzi/palworld-update-palspawner#2]
Does bro have a donation link? Would love to buy you a drink or something :)

**Comment by Tizzi** [comment]
thank you for your kindness but no one will believe I dont have bank account or ewallet account.
no creditcard. but every thing is fine.

**Comment by xCENTx** [comment]
> Does bro have a donation link? Would love to buy you a drink or something :)

consider donating to [UnknownCheats](https://www.unknowncheats.me/forum/misc.php?do=donate)

**Comment by Wet-9** [comment]
I'm interested in donating because no one in UC posted anything about spawn_pal. So I'm merely interested in donating to the first person who would open-source such a function. 

But you've brought up a good point and I will donate to UnknownCheats!
